services:
    infer:
        build:
            context: ./infer
            dockerfile: Dockerfile
        restart: always
        # internal network only
        networks:
            - app

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - DB_PATH=/data/face_reg.db
            - INFER_URL=http://infer:8001
            - JWT_SECRET=${JWT_SECRET}
        volumes:
            - ./data:/data
            - ./api/web:/app/web

        depends_on:
            - infer
        networks:
            - app

networks:
    app:
        driver: bridge
